export const Lang = {
	// ENGLISH
	a: "Comment anywhere",
	b: "Comment on any website or physical location. Earn cryptocurrency tips for your posts or website.",
	c: "Get Started",
	d: "Wallet activities",
	e: "Edit profile",
	f: "Follow",
	g: "Following",
	h: "Enter Url",
	i: "Faq",
	j: "Login",
	k: "Register",
	l: "Logout",
	m: "Hi",
	n: "Recent Tips",
	o: 'Add a topic and make a difference',
	p: "Title field can only contain 140 characters",
	q: "Title field can't be empty",
	r: "Add Topic",
	s: "Topics",
	t: "This post has ",
	u: " comments. Be the first to post.",
	v: "JOIN THE CONVERSATION TODAY",
	w: "Add Comment",
	x: "You have to be",
	y: "Logged In",
	z: "to comment",
	a1: "What are your thoughts?",
	b1: "Comment cryptocurrency on any website and get tipped",
	c1: "Home",
	d1: "You need to be logged in to perform this operation.",
	e1: "Don't have an Account? ",
	f1: "Sign Up",
	g1: "Username",
	h1: "Email",
	i1: "Password",
	j1: "Confirm Password",
	k1: "Log In",
	l1: "Have an account?",
	m1: "New Here? Create an Account...",
	n1: "Unfollow",
	o1: "Give us a sec ☺️. We are getting things ready for you.",
	p1: "I know it been a while but we are working on it 🙏...",
	q1: "It taking too long. Your network must me slow 🚶.",
	r1: "Forgot Password",
	s1: "WELCOME, LOGIN TO YOUR ACCOUNT",
	t1: "Add Coin",
	u1: "Trendings",
	v1: "VOTES",
	w1: "TIPS",
	x1: "FOLLOWERS",
	y1: "NEXT REWARD:",
	z1: "Follow Post",
	a2: "Following Post",
	b2: "Report post",
	c2: "Delete",
	d2: "Member Since:",
	e2: "Post",
	f2: "Favourites",
	g2: "Comments",
	h2: "Enter a Url",
	i2: "Enter a url of your choice and create a post.",
	j2: "Upload",
	k2: "No, Thanks",
	l2: "There currently no topics for this site",
	m2: "Please",
	n2: "to create a topic and earn coin today",
	o2: "Title",
	p2: "Message",
	q2: "Close",
	r2: "Tip's History",
	s2: "Description",
	t2: "Tip Status",
	u2: 'Currency',
	v2: 'Amount',
	w2: 'Date',
	x2: "Leaderboard",
	y2: "Popular",
	z2: "Level",
	a3: "Reward for",
	b3: "Progress",
	c3: 'User Info',
	locale: "en",

	// CHINESE
	// a: "任何地方的评论",
	// b: "。对任何网站或物理位置的评论。以您发的帖子或网站赚取加密货币的奖励",
	// c: "开始吧",
	// d: "钱包活动",
	// e: "编辑个人资料",
	// f: "跟随",
	// g: "以下",
	// h: "输入网址",
	// i: "常见问题解答",
	// j: "登录",
	// k: "注册",
	// l: "登出",
	// m: "你好",
	// n: "最近的贴子",
	// o: '添加一个话题并使之有所不同',
	// p: "标题字段只能包含30个字符",
	// q: "标题字段不能为空",
	// r: "添加话题",
	// s: "话题",
	// t: "这篇文章有",
	// u: " 条评论。 是第一个发帖的",
	// v: "今天加入对话",
	// w: "添加评论",
	// x: "你必须",
	// y: "登录",
	// z: "评论",
	// a1: "你是什么想法",
	// b1: "在任何网站上评论加密货币并获得提示",
	// c1: "家",
	// d1: "您需要登录才能执行此操作。",
	// e1: "没有账户?",
	// f1: "注册",
	// g1: "用户名",
	// h1: "电子邮件",
	// i1: "密码",
	// j1: "确认密码",
	// k1: "登录",
	// l1: "有一个账户？",
	// m1: "新来的？创建一个帐户...",
	// n1: "取消关注",
	// o1: "给我们一个☺️。我们正在为您做好准备。",
	// p1: "我知道已经有一段时间但我们正在研究它......",
	// q1: "这花了太长时间。你的网络必须让我慢一点。",
	// r1: "忘记密码",
	// s1: "欢迎，登录到您的帐户",
	// t1: "添加硬币",
	// u1: "Trendings",
	// v1: "票数",
	// w1: "提示",
	// x1: "追随者",
	// y1: "下一个奖励：",
	// z1: "关注邮政",
	// a2: "关注邮政",
	// b2: "报告帖子",
	// c2: "删除",
	// d2: "会员自：",
	// e2: "岗位",
	// f2: "最爱",
	// g2: "评论",
	// h2: "输入网址",
	// i2: "输入您选择的网址并创建帖子。",
	// j2: "上传",
	// k2: "不用了，谢谢",
	// l2: "目前没有此网站的主题",
	// m2: "请",
	// n2: "创建一个主题，今天赚钱",
	// o2: "标题",
	// p2: "信息留言",
	// q2: "关",
	// r2: "提示的历史",
	// s2: "描述",
	// t2: "提示状态",
	// u2: "货币",
	// v2: '量',
	// w2: '约会',
	// x2: "排行榜",
	// y2: "流行",
	// z2: "水平",
	// a3: "奖励",
	// b3: "进展",
	// c3: '用户信息',
	// locale: "zh_cn",
}